### ISSUE TITLE
Make it compatible with Immutable.js redux store

### ISSUE THREAD

**Issue by tpinne** [LouisBarranqueiro/reapop#11]
Hi,

I really like your module. Sadly it doesn't run out of the box if the complete redux store is based on Immutable.js.

In my case the complete store is immutable. Adding your reducer at top level makes it a key of a Immutable.Map . So changing **line 130 in NotificationsSystem.js** to `notifications: state.get('notifications')` should do the trick. Because you get back a plain JS Object, since your initial state is empty.

**Comment by LouisBarranqueiro** [comment]
Hi @tpinne,

I don't wanna add immutable as dependency just for that. Maybe you should only use immutable in your reducers or find an other way to overcome this. Sorry :(

**Comment by lenybernard** [comment]
Hello, I have got the same problem here, is it really incompatible with immutable or am I missing something ?

**Comment by ziogaschr** [comment]
Hey guys, here is a bit hacky workaround. @LouisBarranqueiro thanks for this nice component.
Please keep in mind to not remove the `export`ed component.

```
import {NotificationsSystem} from 'reapop/lib/components/NotificationsSystem';

class App extends React.Component {
  render() {
    return (
      <NotificationsSystem theme={theme}
                                           notifications={this.props.notifications}
                                           defaultValues={{closeButton: true}}/>
    )
  }
}

const mapStateToProps = state => ({
  notifications: state.get('notifications')
});

// Connect Redux
export default connect(mapStateToProps)(App);
```

p.s.: If you use it like this, keep in mind that it is a Redux anti-pattern. As you store plain JS object for `notifications` inside the state.
