### ISSUE TITLE
notifications are not being rendered 

### ISSUE THREAD

**Issue by jasan-s** [LouisBarranqueiro/reapop#12]
Using redux dev tools I can see that addnotification thunk is adding each notification to the store, however I  dont see any notification render on the page.

**Comment by jasan-s** [comment]
Silly me,  // reducer must be mounted as `notifications` ! . I was custom naming the reducer.

**Comment by lineldcosta** [comment]
Even i am having the same issue.. is the below right?
const reducers = combineReducers({
  form : formReducer,
  User : user,
  Listing : listing,
  notifications: notificationsReducer()
});
