### ISSUE TITLE
defaultValues are not working

### ISSUE THREAD

**Issue by Kuirak** [LouisBarranqueiro/reapop#13]
Unfortunately default values are not working, It comes from the way you destructure  it from props in https://github.com/LouisBarranqueiro/reapop/blob/master/src/components/NotificationsSystem.js#L76

when you destructure like this `defaultValues` is undefined  and it will fallback to the  const defined at https://github.com/LouisBarranqueiro/reapop/blob/master/src/components/NotificationsSystem.js#L8-L15

**Comment by LouisBarranqueiro** [comment]
Yes, could you PR? :)
