### ISSUE TITLE
String IDs are prohibited

### ISSUE THREAD

**Issue by ckald** [LouisBarranqueiro/reapop#14]
Hi again! Setting IDs works exactly as I needed it to!

But I found out that propTypes prohibit setting string IDs. For the time being I'm just hashing strings to ints, but this would be a minuscule change in the code

**Comment by LouisBarranqueiro** [comment]
yes, could you PR and add tests, please? :)

**Comment by LouisBarranqueiro** [comment]
[Reapop v1.0.0](https://github.com/LouisBarranqueiro/reapop/releases/tag/v1.0.0) is released - **Read breaking changes before update** :)

**Comment by ckald** [comment]
Thanks! I haven't gotten around to do this
