### ISSUE TITLE
If buttons are added the dismissAfter doesn't function.   

### ISSUE THREAD

**Issue by jasan-s** [LouisBarranqueiro/reapop#15]

**Comment by LouisBarranqueiro** [comment]
It's not a bug, it a desired behavior. notifications with buttons are like "alert", it require a user action

**Comment by jasan-s** [comment]
@LouisBarranqueiro is it possible to force automatic dismissal even with buttons?

**Comment by LouisBarranqueiro** [comment]
yeah, I'm think about a way to have this behavior :)

**Comment by PredokMiF** [comment]
Hi! It is looks like bug, because if I set `dismissAfter:1000` - I expect that it close after one second.

I have one case:
When I remove record, I show notification about it and hide it after X second - it is ok. But in this alert I have button to revert this action back, and it is broken my convenience.

```store.dispatch(addNotification({
    title: 'Success deletion',
    status: 'success',
    message: 'Record was removed',
    position: 'tr',
    dismissible: true,
    dismissAfter: 5000,
    buttons: [
        {
            name: 'Rollback',
            primary: true,
            onClick: ()=>{/*Rollback action*/}
        }
    ]
}))```

**Comment by LouisBarranqueiro** [comment]
> It's not a bug, it a desired behavior. notifications with buttons are like "alert", it require a user action

so `dismissAfter` is ignored.

but I'm gonna remove this automatic behavior.

**Comment by LouisBarranqueiro** [comment]
[Reapop v1.0.0](https://github.com/LouisBarranqueiro/reapop/releases/tag/v1.0.0) is released - **Read breaking changes before update** :)
