### ISSUE TITLE
Webpack include React even if it in externals

### ISSUE THREAD

**Issue by PredokMiF** [LouisBarranqueiro/reapop#18]
If I load React, Redux etc, as separete scripts and put it to externals in webpack.config.js, webpack  all the same include it in to my bundle and I have: react.js and bundle.js (witn second React).

The problem in file `/src/components/NotificationsContainer.js`, line 2:`import TransitionGroup from 'react/lib/ReactCSSTransitionGroup';` if I comment it, all works good.

I fix it on my side like this:
```externals: {
    'react': 'React',
    'react-dom': 'ReactDOM',
    'redux': 'Redux',
    'react-redux': 'ReactRedux',
    'react-router': 'ReactRouter',
    'redux-logger': 'reduxLogger',
    'redux-form': 'ReduxForm',
    'react/lib/ReactTransitionGroup': 'React.addons.TransitionGroup',
    'react/lib/ReactCSSTransitionGroup': 'React.addons.CSSTransitionGroup',
}```

But I think that it should be fixed on your side.

**Comment by LouisBarranqueiro** [comment]
Hey @PredokMiF,  Try: 
- `npm install react-addons-css-transition-group`
- replace line with `import TransitionGroup from 'react-addons-css-transition-group`

**Comment by PredokMiF** [comment]
I Yes, I already made this, but it is only a hack, I think

**Comment by LouisBarranqueiro** [comment]
It's absolutely not an hack. Just the recommended way by Facebook: https://facebook.github.io/react/docs/animation.html

**Comment by LouisBarranqueiro** [comment]
got some news @PredokMiF ?

**Comment by LouisBarranqueiro** [comment]
[Reapop v1.0.0](https://github.com/LouisBarranqueiro/reapop/releases/tag/v1.0.0) is released - **Read breaking changes before update** :)

**Comment by PredokMiF** [comment]
I fix it with `webpack.DllPlugin`:
First bundle - `'react', 'react-dom', ..., 'reapop', 'reapop-theme-wybo', 'font-awesome/css/font-awesome.min.css'`
Second bundle - my own code.
This plugin can combine librarys in bundle and separate it from your own source code. I like it )
