### ISSUE TITLE
Dismiss all

### ISSUE THREAD

**Issue by human-a** [LouisBarranqueiro/reapop#19]
Hi

Is there a way to dismiss all open notifications?

BTW, nice work!

**Comment by LouisBarranqueiro** [comment]
Hi @human-a ,

No but it can be useful, could you PR? :)

Thanks for using it :)

**Comment by human-a** [comment]
It certainly is useful. I am using reapop in an app and I do need it. I will give it a try and if successful I will create a PR for sure.

**Comment by LouisBarranqueiro** [comment]
Cool

**Comment by LouisBarranqueiro** [comment]
[Reapop v1.0.0](https://github.com/LouisBarranqueiro/reapop/releases/tag/v1.0.0) is released - **Read breaking changes before update** :)

**Comment by human-a** [comment]
That is great. And by the way, sorry if I didn't find the spare time to give it a look.

**Comment by human-a** [comment]
1 more breaking change, maybe should be added to the list:

Before this update, the store config could work with notificationsReducer passed as function expression:

```javascript
const store = createStoreWithMiddleware(combineReducers({
    notifications: notificationsReducer
}), {});
```

But now the notificationsReducer SHOULD be passed as a function declaration, so the new code should like this:

```javascript
const store = createStoreWithMiddleware(combineReducers({
    notifications: notificationsReducer() // Notice this one
}), {});
```

The rest was a smooth upgrade experience for me.

**Comment by LouisBarranqueiro** [comment]
Updated. thanks for your feedback! :)
