### ISSUE TITLE
Any plans for a new release?

### ISSUE THREAD

**Issue by dukedhx** [LouisBarranqueiro/reapop#193]
Not sure if I should ask this in an issue but is there any plans for a new release soon?

There have been many useful updates since the last release 10 months ago including support for the latest Redux and React Redux etc.

One of our most popular projects use reapop so we can really use a new release to enable us to update our Redux and React Redux to the latest versions.

Thanks so much!

**Comment by LouisBarranqueiro** [comment]
Hey @dukedhx, sorry for the late response. It's coming this WE 😄🎉 I will make release more often now that Renovate is here to help.
