### ISSUE TITLE
Will this work with React-native?

### ISSUE THREAD

**Issue by jasan-s** [LouisBarranqueiro/reapop#20]
Very nice library. Love using it. Was wondering if it will also work with react native app using redux.

**Comment by LouisBarranqueiro** [comment]
Hey @jasan-s, 

for the redux part, it should be good but for the components, i'm not sure. I didn't use it with react-native yet. If you try to, give some feedback :)

**Comment by jasan-s** [comment]
will try and update.

**Comment by LouisBarranqueiro** [comment]
Any news? :)

**Comment by jasan-s** [comment]
Never got it to work. If I remember correctly it was because the .css files for this lib. React-native requires .js files with objects for styling. Lib is awesome, would be better if it was universal(native + react). One option is to rewrite using something like [styled-components ](https://github.com/styled-components/styled-components).

**Comment by LouisBarranqueiro** [comment]
I didn't plan to do because this lib is designed for desktop but good to know :)
