### ISSUE TITLE
Have Reapop working with Bootstrap 4 and No Icon shows up with the notification

### ISSUE THREAD

**Issue by vascojm82** [LouisBarranqueiro/reapop#211]
Hi,

I currently have Reapop working with Boostrap v4.3.1 and the icon to the left of the Title and message for the notification doesn't show up:

![image](https://user-images.githubusercontent.com/18554186/66262058-1e92c280-e7a7-11e9-95b6-bc73ba8cbc27.png)

Also, I would like to change the font-size for the message p tag (make it bigger) but I can't find an option to do so on Reapop.

Could someone please help?.

**Comment by LouisBarranqueiro** [comment]
👋 @vascojm82, we are help to help you but please respect the template to report a bug. It helps us to understand your problem and possibly find a solution. Please re-open this issue when you updated it with this template: https://github.com/LouisBarranqueiro/reapop/issues/new?assignees=LouisBarranqueiro&labels=&template=bug_report.md
