### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL on import theme when running Jest test

### ISSUE THREAD

**Issue by kmerhi** [LouisBarranqueiro/reapop#28]
### Configuration

 - **Operating system with version** : 10.12.2 (macOS Sierra)
 - **Browser with version** : Not applicable
 - **Reapop version** : 1.0.0
 - **React version** : 15.4.2
 - **Redux version** : 3.6.0
 - **React-redux version** : 5.0.2
 - **Jest version** : 5.0.2
 

### Actual behavior
Running `jest` tests results in:

```
> FAIL  app/scripts/containers/App.spec.js
Test suite failed to run

    SyntaxError: Unexpected token ILLEGAL

      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at Object.<anonymous> (node_modules/reapop-theme-bootstrap/index.js:3:11)
      at Object.<anonymous> (app/scripts/containers/App.jsx:4:55)
```

### Expected behavior

```
> PASS  app/scripts/containers/App.spec.js
  <App>
    ✓ should exist
```

### Steps to reproduce the behavior
1. Write a simple React component
1. Write a jest test to verify the component is defined
1. Run test, it should pass
1. Add theme import (bootstrap or wybo)
1. Run test again, it will now fail

**Comment by LouisBarranqueiro** [comment]
I think that your test env in not well configured because it works with the one used by this repository. http://stackoverflow.com/a/12719860/3755845

**Comment by kmerhi** [comment]
All my 289 tests pass with the exception of my root component when a reapop theme is included.

Perhaps I missed something here, but I have not seen your test that covers the case where a root component includes a theme.

**Comment by LouisBarranqueiro** [comment]
you are right but if your application works with Reapop in an specific env, and not in your test env, there are many chances that it comes from the env configuration. I had these kind of errors too when I configured the test env for this project.

**Comment by kmerhi** [comment]
I've got some more info with an updated version of jest ("^19.0.2"):
```
 FAIL  app/scripts/admin/info-app/components/Info.spec.js
  ● Test suite failed to run

    /Users/kmerhi/Project/node_modules/reapop-theme-bootstrap/lib/styles.css:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){@charset "UTF-8";
                                                                                             ^
    SyntaxError: Invalid or unexpected token

      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at Object.<anonymous> (node_modules/reapop-theme-bootstrap/index.js:3:11)
      at Object.<anonymous> (app/scripts/admin/info-app/components/Info.jsx:7:29)
```
Perhaps it could shed light on this issue?

**Comment by LouisBarranqueiro** [comment]
I'm gonna use jest for a project with reapop soon, so I'm gonna tell you if I encounter a similar error.

**Comment by jongrover** [comment]
I know this is closed thread, but I get the same error using bootstrap-only-css npm package. It errors on the top of CSS files @charset command. This file is imported into my App component in order to style it. Here is the actual error:

```
.../node_modules/bootstrap-only-css/dist/bootstrap.css:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){@charset "UTF-8";
                                                                                             ^
    SyntaxError: Invalid or unexpected token
```
