### ISSUE TITLE
Feature Request: Markdown Support

### ISSUE THREAD

**Issue by bryandbor** [LouisBarranqueiro/reapop#29]
I want to propose an additional feature for Reapop.

I think you've done a great job on the library so far, but I want to recommend adding Markdown support in `title` and `message` properties. This would be a safer way to allow for styled text without the risk of allowing html directly. There are numerous open-source React markdown renderers. Let me know if you would like me to elaborate; however, I think the concept is simple enough.

**Comment by LouisBarranqueiro** [comment]
Hey @bryandbor, We don't really need it since html allow us to do everything. Also we have to add a dependency for that. About the security aspect, you can control if you wanna to set html or not and you can also control and strip what's in here before creating the notification.
