### ISSUE TITLE
Feature Request: Input Field

### ISSUE THREAD

**Issue by bryandbor** [LouisBarranqueiro/reapop#30]
I think we should add a status type for `input` which would include an input field under/within a notification similar to that of OSX. In OSX, some notifications have an input area for quick responding (such as iMessage); these are usually only single line inputs. I think this would help as the notification could now also take the place of a `prompt()` and return textual feedback from the user in the form of a triggered callback function upon user completion.

**Comment by LouisBarranqueiro** [comment]
I don't wanna implement such a feature because I wanna keep Reapop the simplest as possible. Reapop has a redux and react part so you can create your own `InputNotification` component.
