### ISSUE TITLE
Image + status

### ISSUE THREAD

**Issue by NeXTs** [LouisBarranqueiro/reapop#305]
image: "When an image is defined, status of the notification is set to default."

Is it possible to bypass this rule somehow without creating whole custom theme?
I need to show image + use "success" and "info" statuses at the same notification.
Also I'd like to add custom styles to image, is there any way to do it in easy manner?

**Comment by LouisBarranqueiro** [comment]
👋  @NeXTs

yes, this is an opinionated default behavior that I plan to remove to make the library more customizable. Just so you know, I'm currently working on a complete rewrite of this library:
- written in typescript, types exposed
- support for react hooks
- new styling APIs (inline CSS or CSS files)
- new themes, new transitions
- customizable components and transitions
- no default behavior
- pure action creators (remove `redux-thunk` dependency)
etc...) 
- works with react only, and pluggable with redux, mobx, or any other application state manager

I will probably release it in 2 or 3 weeks.

What you need, will be possible with the new version. By curiosity, could you show me the result you would like to obtain? Do you already have a custom theme? Do you display the icon + an image?

**Comment by LouisBarranqueiro** [comment]
👋 @NeXTs , I just created an issue to share the changes: https://github.com/LouisBarranqueiro/reapop/issues/308. If you have any feedback regarding the current version, or things you would like to have, feel free to post a comment on the issue :)

**Comment by LouisBarranqueiro** [comment]
@NeXTs I forgot about it but this behavior was already removed in the [v2.0.0](https://github.com/LouisBarranqueiro/reapop/releases/tag/v2.0.0)

**Comment by NeXTs** [comment]
Thank you!

![images](https://user-images.githubusercontent.com/1753208/99362871-b163c300-28bc-11eb-8c14-9d295a740225.png)
