### ISSUE TITLE
Feature Request: Pure actions that don't require a middleware

### ISSUE THREAD

**Issue by bobbydixit** [LouisBarranqueiro/reapop#31]
It would be better if all actions were pure. i.e. not dispatching any other action so that user can use the library without any middleware. or even when user is using some other middleware like redux-saga. even then they should be able to use the library

**Comment by LouisBarranqueiro** [comment]
Hey @bobbydixit, I currently don't have time to do that. Could you give it a try?

**Comment by bobbydixit** [comment]
@LouisBarranqueiro I am busy this week will give it a shot next week

**Comment by gabrielrtakeda** [comment]
It would be great to not have the dependency of a specific middleware.

## +1 for this

**Comment by bobbydixit** [comment]
@LouisBarranqueiro the only solution I can think of is to move all the logic that's there in actions in src/store/notifications.js to a component and maybe even addition of extra states, do you have any issue with this approach, if none then I will start working on it

**Comment by LouisBarranqueiro** [comment]
what are the problems that you encounter?

**Comment by bobbydixit** [comment]
@LouisBarranqueiro  
I have made the actions pure
https://github.com/LouisBarranqueiro/reapop/pull/35

But there is an issue in making the actions pure
https://github.com/LouisBarranqueiro/reapop/pull/35/files#diff-f47aa5e84c4ac474ee15b86e589c6779R40
Implementation for update notification will change
Notification object won't be returned directly instead it would be inside payload 
let me know if you have an issue with this implementation.

I wl modify the test after we have finalized implementation for update notification

**Comment by JonnyHeavey** [comment]
Would love to see this improvement

**Comment by LouisBarranqueiro** [comment]
I'm thinking about this, not decided yet but to take the right decision regarding the implementation I would like to understand why you need pure actions? Do you use redux-saga? or another middleware? 
Could you please update this issue with this template https://github.com/LouisBarranqueiro/reapop/issues/new?assignees=LouisBarranqueiro&labels=&template=feature-request---improvement.md ? @bobbydixit 

 Could you please do the same @JonnyHeavey by commenting on this issue?

**Comment by brandondurham** [comment]
I was so set on this package until I saw that it requires Thunk middleware. That isn’t an option in my case. I don’t think I would have set it up that way even if it were. It’s an odd requirement.

I _may_ be able to help with this change if anyone wants to pair up! Lemme know.

**Comment by LouisBarranqueiro** [comment]
This will be done in the new version. More information in https://github.com/LouisBarranqueiro/reapop/issues/308

**Comment by LouisBarranqueiro** [comment]
I just released the [v3.0.0](https://github.com/LouisBarranqueiro/reapop/releases/tag/3.0.0) of Reapop. This is done. :)
