### ISSUE TITLE
Support ssr?

### ISSUE THREAD

**Issue by saeedPadyab** [LouisBarranqueiro/reapop#319]
hello
any plan to support ssr?? it's better to compatible with nextjs applications

**Comment by LouisBarranqueiro** [comment]
👋 @saeedPadyab, I don't know if the library is support SSR. It would be great. Did you try it out? Did you encounter a bug? If yes could you please add all the information so I can understand the problem and potentially fix it? Please re-open this issue when you updated it.

**Comment by saeedPadyab** [comment]
> 👋 @saeedPadyab, I don't know if the library is support SSR. It would be great. Did you try it out? Did you encounter a bug? If yes could you please add all the information so I can understand the problem and potentially fix it? Please re-open this issue when you updated it.

sure
