### ISSUE TITLE
Support SSR

### ISSUE THREAD

**Issue by saeedPadyab** [LouisBarranqueiro/reapop#321]
As you know we don't access the window and document objects in the node apps but your library needs them to work properly. when I added that in my app I encountered this error "window is undefined"

**Comment by LouisBarranqueiro** [comment]
👋 @saeedPadyab no need to open a new issue, I meant to edit the previous one. Anyway, could you follow the template to report a bug here: https://github.com/LouisBarranqueiro/reapop/issues/new?assignees=LouisBarranqueiro&labels=&template=bug_report.md&title=

**Comment by mihirgupta0900** [comment]
@saeedPadyab I don't think you have to change anything in the package for it to work with ssr. 
If you are working with Gatsby, you could follow [this ](https://www.gatsbyjs.com/docs/using-client-side-only-packages/) guide and if you are using Next, [this](https://nextjs.org/docs/advanced-features/dynamic-import) guide (import module in useffect hook) could help you.

**Comment by LouisBarranqueiro** [comment]
Thanks for the tip @mihirgupta0900. I will check that out this week end with Next.js and update the package in case it does not support SSR
