### ISSUE TITLE
Notifications not showing

### ISSUE THREAD

**Issue by villagra** [LouisBarranqueiro/reapop#327]
Hello Louis,
I'm trying to integrate your very nice notifications system, but I can't get the notifications to show up... I see the notifications arrive to the notificationsystem component but they don't show up

![image](https://user-images.githubusercontent.com/1038513/101638869-e8964180-3a2e-11eb-836f-b2ee0b5d794c.png)

### Environment
 - Latest win10
 - Latest Edge Version 87.0.664.57
 - reapop; 3.0.0
-  react-redux 7.2.2

I think I have everything wired up correctly but maybe I am missing something important in the setup... any ideas?

Thanks a lot.

**Comment by LouisBarranqueiro** [comment]
👋 @villagra, Thanks, I appreciate that 🙏 . 

I see that you have some notifications in the store but all notifications containers are empty. Did you add a `position` attribute to your notifications? Could you send me the payload of one of these notifications, as well as the code where you add the `NotificationsSystem` component?

**Comment by villagra** [comment]
Thanks for getting back to me 🤘
The Notifications system is inside a "layout" component:

```
import NotificationsSystem, {atalhoTheme, dismissNotification} from 'reapop'

...............

render() {
      const { history } = this.props;
      return (
        <>
          <NotificationsSystem 
              theme={atalhoTheme}
              dismissNotification={(id) => dismissNotification(id)}
              notifications={this.props.notifications} />

          <div className="wrapper">
              <MainSideMenu 
                  pathName={history.location.pathname}
                  isOpen={this.state.isOpen} 
                  user={this.props.auth}
                  onCloseHandler={this.onCloseHandler}></MainSideMenu>
              <div id="content">
                <nav className="ub-navbar navbar navbar-expand-lg navbar-light fixed-top bg-ubben-light">          
                    <button className="btn-menu btn" type="button" onClick={this.buttonClickHandler}>
                        <span className="navbar-toggler-icon"></span>                
                    </button>
                    <div className="navbar-text">
                        
                    </div>
                    <div className="navbar-text ml-auto header-user-menu">
                      {this.renderHeaderMenu()}
                    </div>            
                </nav>
                {this.props.children}              
              </div>
          </div>   
        </>
    );
  }
}

const _withRouter = withRouter(LayoutSideMenu);

const mapStateToProps = (state) => {
  return {
    auth: state.auth,
    notifications: state.notifications
  }
}

export default connect(mapStateToProps)(_withRouter);
```
And notifications are being sent like the ones in the example....

```
    onClick(evt){
        evt.preventDefault();

        this.setState({
            inprogress: true,
            message: "Please wait"
        });
        
         this.props.notify('This is a test', 'info');        
         console.log("notified");
    }

    render(){        
        return (                        
            <button type="button" 
                    id="teeeeest"
                    disabled={this.state.inprogress} 
                    onClick={this.onClick} 
                    className="btn btn-outline-primary">
                        {this.state.message}
                    </button>
        )
    }
}

const mapDispatchToProps = {
    notify
};

export default connect(null, mapDispatchToProps)(PurchasePackButton);
```

**Comment by LouisBarranqueiro** [comment]
thanks for the details. Did you [set up the default position for your notifications](https://github.com/LouisBarranqueiro/reapop/blob/master/DOCUMENTATION.md#set-default-notifications-attributes)?

If not, try:
```js
this.props.notify('This is a test', 'info', {position: 'top-right'}); 
```
or 
``` js
// run this function when your application starts before creating any notifications
setUpNotifications({
    defaultProps: {
        position: 'top-right',
    } 
})
```

**Comment by villagra** [comment]
That was it! Thanks a lot. 
I did follow the Integration & usage guide at the homepage but did not see that section in the documentation.... As a suggestion, add a reference to that section in the homepage will help future users like me. 👌

**Comment by LouisBarranqueiro** [comment]
Most definitely. I will do that.

**Comment by IggsGrey** [comment]
> 
> 
> Most definitely. I will do that.

A reminder that this hasn't been done yet. I missed this as well.

This issue saved me btw.

**Comment by LouisBarranqueiro** [comment]
Done.
