### ISSUE TITLE
Demo site seems to crash after first notification dismisses

### ISSUE THREAD

**Issue by Seanmclem** [LouisBarranqueiro/reapop#328]
### Description
This is in mobile Chrome for me. Here https://louisbarranqueiro.github.io/reapop after the first demo notification shows a spinner, then success, then just a white screen. Site seems to crash

### Expected behavior
The site should probably stay open. And allow you to test more notifications.

### Steps to reproduce the bug
 Go to https://louisbarranqueiro.github.io/reapop/ and wait five seconds

### Environment
 Up-to-date Android mobile Chrome

### Additional information
- [ ] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
👋 @Seanmclem,

Could you please share the version of your device and chrome app? I tested on IOS 14.1 with chrome 86, and Android 10 with chrome 87, and it works well. Would you be able to get some error messages with [Remote Debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging). I would really appreciate that 🙏

**Comment by LouisBarranqueiro** [comment]
@Seanmclem  I'm closing this issue because it is stale. Feel free to re-open it if you still encounter this problem 🙂 .
