### ISSUE TITLE
button's onClick not being called

### ISSUE THREAD

**Issue by or2008** [LouisBarranqueiro/reapop#336]
### Description
![image](https://user-images.githubusercontent.com/3414979/103157262-cc79fa80-47b9-11eb-93e1-784c0cc4c85d.png)

when clicking on "Details" button, it does not fire my alert function, instead, it just dismisses the notification

**Comment by LouisBarranqueiro** [comment]
👋 @or2008, sorry for the late reply. Can't believe I missed this. I'm on it.

**Comment by or2008** [comment]
works perfectly, Thanks!
