### ISSUE TITLE
Support React 15.5 deprecations

### ISSUE THREAD

**Issue by sabarasaba** [LouisBarranqueiro/reapop#34]
React 15.5 deprecates createClass, PropTypes and ReactTestUtils. These need to be reflected in the codebase to avoid warnings & future incompatibility.

**Comment by ingro** [comment]
I just created a [PR](https://github.com/LouisBarranqueiro/reapop/pull/38) that should fix the warnings.

**Comment by sabarasaba** [comment]
@ingro awesome, well done man!
