### ISSUE TITLE
Reapop usage outside components

### ISSUE THREAD

**Issue by mmesar** [LouisBarranqueiro/reapop#367]
Is there a way to upsert notification outside react components. For example I have custom axios js instance that I use for my API calls. On that axios instance are defined request and response interceptors.  I would like to upsert notification inside interceptor if some kind of error happens. I guess I could do it with redux but, I would like to avoid redux. So... is upserting notification possible outside components and without using redux? I hope I made my case clear.

**Comment by LouisBarranqueiro** [comment]
👋 @mmesar yes, I see what you mean :) Well, the only way that I see would be to pass a reference of the function `notify` to a function responsible for creating this interceptor, when your React app mounts for the first time.

**Comment by LouisBarranqueiro** [comment]
@mmesar Feel free to re-open this issue if you still need help 🙂

**Comment by cuongdevjs** [comment]
no way to do that?

**Comment by LouisBarranqueiro** [comment]
@cuongdevjs Did you see my previous answer?
