### ISSUE TITLE
Prop `className` did not match. Server: "reapop__container reapop__container--top-center reapop__container--single" Client: "reapop__container reapop__container--top-center"

### ISSUE THREAD

**Issue by shehi** [LouisBarranqueiro/reapop#371]
After installing reapop into my NextJs application, I am getting the following error:

![image](https://user-images.githubusercontent.com/653569/110840395-f5803680-82a4-11eb-994b-7660500d899d.png)

Any idea how to solve this? My `./pages/api/_app.tsx` file looks like this:

```
import type { AppProps } from 'next/app';
import { Provider } from 'react-redux';
import { useStore } from '../store';
import '../styles/style.scss';
import { ReactElement, useEffect } from 'react';
import getCsrfCookieAction from '../actions/getCsrfCookie';
import NotificationsSystem, { atalhoTheme, dismissNotification } from 'reapop';

function Application({ Component, pageProps }: AppProps): ReactElement {
    const store = useStore(pageProps.initialReduxState);

    useEffect(() => {
        console.log('app.tsx : Run useEffect()');
        const csrfCookieState = store.getState().getIn(['csrfCookie']);
        if (csrfCookieState !== true) {
            store.dispatch(getCsrfCookieAction());
        }
    }, [store]);

    const notifications = store.getState().getIn(['notifications']);

    return (
        <Provider store={store}>
            <Component {...pageProps} />
            <NotificationsSystem
                // 2. Pass the notifications you want Reapop to display.
                notifications={notifications}
                // 3. Pass the function used to dismiss a notification.
                dismissNotification={(id: string) => store.dispatch(dismissNotification(id))}
                // 4. Pass a builtIn theme or a custom theme.
                theme={atalhoTheme}
            />
        </Provider>
    );
}

export default Application;
```

and index page at `./pages/index.tsx`:
```
import Head from 'next/head';
import React, { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import styles from '../styles/Home.module.scss';
import Footer from '../components/Layout/Footer';
import Header from '../components/Layout/Header';
import { notify } from 'reapop';

const Home: React.FC = () => {
    const dispatch = useDispatch();

    useEffect(() => {
        // 3. Create a notification.
        dispatch(notify('Welcome to the documentation', 'info'));
    }, [dispatch]);

    return (
        <>
            <Head>
                <title>GuildPlanner.Pro</title>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header />

            <main className={styles.main + ' container'}>
                <h1>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>
            </main>

            <Footer />
        </>
    );
};

export default Home;
```

Reducer is in its place. I can see reapop divs populated:

![image](https://user-images.githubusercontent.com/653569/110840871-87883f00-82a5-11eb-8e4e-59da4f4f5fb5.png)

**Comment by LouisBarranqueiro** [comment]
👋 @shehi, this is not an error just a warning (See the message on the first image you sent). This message appears because the notifications container is rendered first without the `window` global variable (when rendered on the server). Because of that, the library simulates that the width of the window is `0` and notifications will be rendered in the same "special" notifications container (`reapop__container--single`). Then when the component is mounted on the client, the HTML won't match the one generated on the server because the current width of the window is different.

There is no problem with that and I'm not sure I can do something about it. I will try something, and basically do the opposite: if the `window` is not available, we won't render notifications in a single container.

**Comment by LouisBarranqueiro** [comment]
I tried something and it didn't solve this warning, just moved the "problem".  You might want to check this issue: https://github.com/vercel/next.js/issues/11600 to hide this type of warning.

**Comment by shehi** [comment]
Would it be because of possible misconfiguration from my part? Learning NextJs fresh here, I am kinda not sure if I misconfigured some component. Ok, thank you!

**Comment by LouisBarranqueiro** [comment]
> Would it be because of possible misconfiguration from my part?

Not misconfiguration but maybe missing configuration to hide this type of warning because these situations can occur and it's completely normal. 

> Addendum: Is reapop strict mode compatible? vercel/next.js#11600 (comment)

What does it mean? you can use reapop with React strict mode, if that's the question. It does not matter.

**Comment by augiwan** [comment]
Just leaving this here in case it helps someone.

If you're using Next and you face these types of hydration issues and you really don't need SSR across your app, you can simply do this in your `_app.js`:


```
import dynamic from "next/dynamic";

// Remove this -> export default App;
// And replace with this:
export default dynamic(() => Promise.resolve(App), {
  ssr: false,
});
```
