### ISSUE TITLE
The callbacks in the NotificationsProvider should be wrapped in useCallback

### ISSUE THREAD

**Issue by Kingdutch** [LouisBarranqueiro/reapop#372]
### Description
The callbacks in the NotificationsProvider (`notify`, `dismissNotification`, `dismissNotifications`) are not wrapped in useCallback. This means that they're recreated every time a notification is created or dismissed. This breaks equality checks in downstream components (for example when notifying from a `useEffect`).

Removing `notify` from the dependencies is not the right solution. The React team even made an ESlint rule for this.

Adding a correct invocation of `useCallback` for each callback with a dependency on `dispatch` (and possibly also the externally imported functions) would solve the issue.

### Expected behavior
Notifications in use-effect with a correct dependency on the `notify` function from the `NotificationsProvider` should only trigger once.

### Steps to reproduce the bug
The following code would cause endless notifications.

```
useEffect(() => {
  notify("Hello world");
}, [notify]);
```

### Environment
 - **OS name and version** : OS X Big sur
 - **Browser name and version**: Firefox
 - **Reapop version**: 3.0.3

### Additional information
- [ ] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
👋 @Kingdutch You're right. I will fix that. 👍

**Comment by akarsh-k** [comment]
Hi @LouisBarranqueiro, You haven't released this fix to npm yet. Could you please help to push this to npm?

**Comment by LouisBarranqueiro** [comment]
👋 @akarsh-k , just published 🙂

**Comment by akarsh-k** [comment]
@LouisBarranqueiro, Thanks for your help, really appreciate it! :)
