### ISSUE TITLE
GPL license

### ISSUE THREAD

**Issue by codepunkt** [LouisBarranqueiro/reapop#39]
Thanks for your great work on this project.

Just wanted to let you know that GPL licensing makes it impossible to use in a lot of circumstances where the source can not be disclosed - which it wouldn't if it was MIT. Is this intended?

**Comment by LouisBarranqueiro** [comment]
You're welcome. :)

Yes, it is for the moment. Maybe i'll change the license. What you would like to do with reapop?

**Comment by codepunkt** [comment]
I considered using it in an enterprise environment where GPL licensing is strictly prohibited :)

**Comment by LouisBarranqueiro** [comment]
Project is now under MIT license  🎉 . Have fun @codepunkt :)
