### ISSUE TITLE
Updating notification throws state mutation error with redux-toolkit

### ISSUE THREAD

**Issue by pharmarin** [LouisBarranqueiro/reapop#394]
### Description
When updating notification, redux-toolkit throws error : `Invariant failed: A state mutation was detected between dispatches, in the path 'notifications.0.status'`
I had to disable immutableCheck middleware for notifications in redux store. 

### Expected behavior
Dispatching `notify` should return a new object instead of state reference, I suppose. 

### Steps to reproduce the bug
Configuring store as the documentation

### Environment
 - **OS name and version** : MacOS 10.15.7
 - **Browser name and version**: All 
 - **Reapop version**: 3.0.4

### Additional information
- [ ] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
👋 @pharmarin,  Could you please share some code (an example) so I can reproduce this problem?

**Comment by pharmarin** [comment]
I made a [CodeSandbox](https://codesandbox.io/s/reapop-state-mutation-gg1dq?file=/src/App.tsx) reproducing the problem. Uncommenting the lines resolves the problem (it excludes notifications from immutability checking).

**Comment by LouisBarranqueiro** [comment]
> I made a CodeSandbox reproducing the problem. 

Well, I didn't expect that much. 😄 that's great! I will check that out.

>  I really like your package and the look it has.

Really appreciate that! Thanks for using it! 🙂

**Comment by shehi** [comment]
I switched to react-toolkit as well, and started to get this error. Any chance we could get a fix for this?

**Comment by LouisBarranqueiro** [comment]
I will try to check this out this WE.

**Comment by cuongdevjs** [comment]
> I will try to check this out this WE.

Please tell me when any updates. I installed this lib on my project, but I just checked I can't use It outside react (axios configure file) and can't integrate with redux-toolkit.

**Comment by LouisBarranqueiro** [comment]
👋 guys, new version should fix this problem. Please re-open the issue if you still have an issue.

**Comment by NeXTs** [comment]
> 👋 guys, new version should fix this problem. Please re-open the issue if you still have an issue.

Hello, I get mutation error updating notification in Class component.
