### ISSUE TITLE
Middleware idea

### ISSUE THREAD

**Issue by Arturszott** [LouisBarranqueiro/reapop#4]
Hey. I wanted to ask If you are interested in introducing middleware for handling simple object based actions (testable!).

I've introduced this in our app and it works well.

```javascript
import { addNotification } from 'reapop';

const ACTION_TYPE = '__SEND_NOTIFICATION__';

const notificationMiddleware = () => (next) => (action) => {
    if (action.type && action.type === ACTION_TYPE) {
        return next(addNotification(action.payload));
    }

    return next(action);
};

export default notificationMiddleware;

export const createNotification = (payload) => {
    return Object.assign({}, {
        type: ACTION_TYPE,
        payload
    });
};
```

**Comment by LouisBarranqueiro** [comment]
Hey @Arturszott, what the benefit of this implementation?

**Comment by Arturszott** [comment]
When I'm testing redux actions I can now check if dispatch was called with the object, which was not available when we were dealing with thunk. function instance !== function instance. 

Plain objects are iteratable so I can write:

````javascript
expect(dispatch).to.have.been.calledWith({
   type: '__SEND_NOTIFICATION__',
   payload: { status: 'error', title: 'Errrrrr', message: 'something went wrong' }
})
```

**Comment by LouisBarranqueiro** [comment]
I don't understand the benefit of this test, since we already test each action creators ?

**Comment by Arturszott** [comment]
Sure. Action creators are tested by itself, but I want to make sure in my action file, that I'm passing the right set of data to it. I can't do this when actionCreator is returning a thunk, because parameters are held inside within the closure.

**Comment by LouisBarranqueiro** [comment]
I'm sorry man but I still don't understand why do you want to check its parameter since we test each actions creators by checking the result in the store. Eg ([source](https://github.com/LouisBarranqueiro/reapop/blob/master/test/store/notifications.test.js#L26-L43)) : 
```js
it('should create an action to add a notification ' +
        '(add `id` property and convert status)', () => {
        notification.id = null;
        // we remove the image, otherwise `treatNotification()` helper will update
        // status of notification
        notification.image = null;
        // here we simulate an HTTP success status code (200 = OK)
        notification.status = 200;
        const notificationAdded = store.dispatch(addNotification(notification));
        const expectedAction = [{
          type: types.ADD_NOTIFICATION,
          payload: Object.assign({}, notification, {
            id: notificationAdded.id,
            status: SUCCESS_STATUS
          })
        }];
        expect(store.getActions()).toEqual(expectedAction);
      });
```
that's why these [tests](https://github.com/LouisBarranqueiro/reapop/blob/master/test/store/notifications.test.js#L19-L76) are enough to be sure that if we add a notification `{ status: 'error', title: 'Errrrrr', message: 'something went wrong' }` with `addNotification` (async action creator), the store will contains an action `{type: 'ADD_NOTIFICATION', payload: { id:1231231234, status: 'error', title: 'Errrrrr', message: 'something went wrong' }`.

**Comment by Arturszott** [comment]
Hmm. Okay, now I get your way of thinking.

For me this kind of test is introducing too much boilerplate into the testing code. That was the reason why I decided to create this middleware. I like my test with the least configuration possible. For testing with store is has to be set first and configured.

Thanks for reviewing my idea anyway. I wanted to share the idea of the code, that actually works for me, but what works for me must not necessary work for you!
