### ISSUE TITLE
notify.error("Message", STATUSES.error) not showing as error

### ISSUE THREAD

**Issue by hinchley2018** [LouisBarranqueiro/reapop#411]
### Description
When using `STATUSES.error` it doesn't format notification as error (STATUS.error color defined [here](https://github.com/LouisBarranqueiro/reapop/blob/main/src/themes/bootstrap.ts#L12)

### Expected behavior
when using `notify("Message",STATUSES.error)` it should format the notification as an error, but it seems to display as status: none
![Screen Shot of Notification](https://user-images.githubusercontent.com/17077365/122989041-fb87b800-d367-11eb-824b-93f1938dcb50.png)
![Screen Shot of React Tools NotificationsSystem](https://user-images.githubusercontent.com/17077365/122990145-3a6a3d80-d369-11eb-8250-ed70dea7639a.png)

### Steps to reproduce the bug
```
npx create-react-app reapop-spike
npm install reapop
```
Add the stuff from the [docs](https://github.com/LouisBarranqueiro/reapop)

Or you can look at my example [here](https://github.com/hinchley2018/reapop-spike) I created a new project with the intent of not having any side-effects from bootstrap or other packages

### Environment
 - **OS name and version** : MacOS **and** Windows 10
 - **Browser name and version**: Chrome 91.0.4472.114 (Official Build) (x86_64) **and** FireFox 89.0 (64-bit)
 - **Reapop version**: ^4.0.0
 - **React version**: ^17.0.2

### Additional information
- [ ] I can fix this bug

**Comment by hinchley2018** [comment]
I also tried `notify("failed to load users", {status: STATUSES.error})` but it still gives me status:none when inspecting with React dev tools

**Comment by hinchley2018** [comment]
Looked into demo source where this works. 
By passing a notification object this has the correct behavior 
```
const errorNotification = {
    message:"Problem loading users", 
    status: STATUSES.error
}
notify(errorNotification)
```
So I think we could be clearer in the docs if this is the intended behavior?
@LouisBarranqueiro should I close this issue?

**Comment by LouisBarranqueiro** [comment]
👋 @hinchley2018, sorry for the late reply. I missed this notification. `notify('message', STATUSES.error)` and `notify('message', {status: STATUSES.error})` should work. Do you use redux or only react? Could you please give me a sample of the code so I can reproduce this issue? It can be on codesandbox.io.

**Comment by hinchley2018** [comment]
@LouisBarranqueiro 
I linked a minimal example only using React above. https://github.com/hinchley2018/reapop-spike

**Comment by LouisBarranqueiro** [comment]
I found why. I will fix that quickly.
