### ISSUE TITLE
Need instructions to use with Next Js

### ISSUE THREAD

**Issue by rhythmbhiwani** [LouisBarranqueiro/reapop#427]
### Description

I wanted to use this package with my next js project with typescript, but it is constantly giving me errors like ```typeerror: cannot destructure property 'notifications' of '(0 , reapop__webpack_imported_module_5__.usenotifications)(...)' as it is undefined.```
I tried to use it with create react app, it worked but not able to make it work with Server Rendered Next Js App. I do not use Redux

### Expected behavior

Using this library as instructed, show not give error and show notifications when triggered.

### Steps to reproduce the bug
 
I am not using Redux, so I followed the install instructions for React alone. I added the NotificationsProvider and NotificationsSystem to the _app.tsx file as it is the root for Next Js Project. (I also tried with creating a different Layout File and using there, but same errors).  When using this line ```const {notifications, dismissNotification} = useNotifications()```, the above stated error shows up.
It would be great if I can get instructions on how to use it with next js, or a example with codepen or anything like that would be appritiated.

### Environment
 - **Windows 10** : 
 - **Google Chrome v92**:
 - **4.0**:

### Additional information
- [ ] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
👋 @rhythmbhiwani, I recently used next.js for a project and it works fine. Could you share an example so I can reproduce this problem?

**Comment by rhythmbhiwani** [comment]
Thanks @LouisBarranqueiro for your reply. Now I fixed the issue, I was not properly following the instructions. Just one feature I'm still not able to user. I want to update notifications, but typescript is showing so many errors. Can you please show some example of updated notifications using typescript

**Comment by LouisBarranqueiro** [comment]
> but typescript is showing so many errors

What are these errors?

There are some examples in the [demo](https://github.com/LouisBarranqueiro/reapop/tree/main/demo): https://github.com/LouisBarranqueiro/reapop/blob/main/demo/src/components/Demo/Demo.tsx#L42

**Comment by LouisBarranqueiro** [comment]
👋 @rhythmbhiwani, closing the issue. Please re-open it if you still have some problem or questions. 🙂
