### ISSUE TITLE
reapop > react-addons-css-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+

### ISSUE THREAD

**Issue by stefensuhat** [LouisBarranqueiro/reapop#43]
### Configuration

 - **Operating system with version** :  Windows 10
 - **Browser with version** : Chome 
 - **Reapop version** : ^1.0.0
 - **React version** : ^ 15.5.4
 - **Redux version** : ^3.6.0
 - **React-redux version** : 5.0.5
 
```
warning reapop > react-addons-css-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+. We recommend you use CSSTransitionGroup from 'react-transition-group' instead.
```

**Comment by Arturszott** [comment]
Hey! I just saw that they fixed it in reapop 19 days ago. What we need is just a new release!

Cheers

**Comment by LouisBarranqueiro** [comment]
done :)
