### ISSUE TITLE
Undefined payload

### ISSUE THREAD

**Issue by tasiodev** [LouisBarranqueiro/reapop#454]
Following the example of the documentation, the payload remains undefined, so I cannot update the notification:

![image](https://user-images.githubusercontent.com/39553179/146172637-da89fbe9-b090-4895-ad0e-45db864f04ce.png)

The code:

```
useEffect(() => {
        const { payload: notification } = notify('Uploading your file...', 'loading', {
            dismissible: false
        })
        // simulate file upload
        setTimeout(() => {
            notification.status = 'success'
            notification.message = 'Your file has been uploaded'
            notification.dismissible = true
            notification.dismissAfter = 5000
            notify(notification)
        }, 2000)
    }, [])
```

Am I doing something wrong?

**Comment by LouisBarranqueiro** [comment]
👋 @tasiodev, could you please fill the template to report a bug? It will help me understand the problem you have. Please re-open this issue once you updated the issue. 🙂

**Comment by yuis-ice** [comment]
I'm facing the same problem.

**Comment by NeXTs** [comment]
Same here.
@LouisBarranqueiro I see that notification update works in demo with functional component and useDispatch.
I use latest reapop version in Class component with redux. 
I do notify dispatching like this
`notify: bindActionCreators(notify, dispatch)`
and then do
`const n = notify({...});`
notifications shows, it works, but **n is undefined**, it does not return {payload, type} object.
how is that possible?

**Comment by NeXTs** [comment]
I managed to get {payload, type} object from **notify** before it is dispatched.
Once it's wrapped with dispatch, it always returns undefined.
I can not understand how it works [here](https://github.com/LouisBarranqueiro/reapop/blob/f2c78af119717cc5a99159b13e13ffdee7e8f1b2/demo/src/components/NotificationButtons/NotificationButtons.tsx#L23), how you managed to get payload AFTER dispatch. 
I have exact same react-redux package version, but mine dispatch does not return the value.

**Comment by LouisBarranqueiro** [comment]
👋 @NeXTs, sorry for the late reply. I've been really busy these days. Could you please open a new issue with all the information so I can reproduce the problem and look into it?

**Comment by NeXTs** [comment]
Hello, it was more of a [question](https://github.com/LouisBarranqueiro/reapop/issues/454#issuecomment-1238691218) than an issue.
I got needed params from notify object **before dispatching**, I was just curious how did you managed to get these params **after dispatching**, because all I got after dispatching is `undefined`.

**Comment by LouisBarranqueiro** [comment]
@NeXTs yes, I understand but if you want me to investigate the matter, I will need more information and an easy way to reproduce the problem. That's why a new issue is more appropriate. If you could set something up in codesandbox or something similar that would be great. 🙂
