### ISSUE TITLE
Attaching Notification OnClick events to the specific notification

### ISSUE THREAD

**Issue by Calebvh** [LouisBarranqueiro/reapop#456]
Hello,

I have a question about how to connect a button's onclick event to whichever notification has been pressed. 

This is part of my current implementation: 
![Capture](https://user-images.githubusercontent.com/21250593/147767793-496a8585-1970-4bb3-9d49-b53a2b3f0c49.PNG)

Essentially I have different types of notifications being fired off with different details tied to each notification for the user to see. Is there a way to pass the notification ID or some other parameter so that the function can determine which data to display? Or is there a different way to go about this?

Thanks!

**Comment by LouisBarranqueiro** [comment]
👋 @Calebvh, 

Sorry for the late reply. I kind of understand the need but it does not seem so appropriate to pass a generic function to all notifications and customize behaviors inside that function based on the notification that was triggered. It makes things more complicated and harder to predict. It would be more appropriate to pass a customized `onClick` function to each notification. Is there anything preventing you from doing that? What were your motivations?

**Comment by Calebvh** [comment]
Hi Louis, 
Thanks for getting back to me. I did end up doing your solution of making a custom onClick for each notification. 

My thinking was when I asked the question I could pass in the id of the notification that was clicked and then go and grab the response details related to that notification from the redux store, but I was able to just update the notification's OnClick method after I had received the message from the backend.  You can mark this ticket as closed, Thanks!

**Comment by LouisBarranqueiro** [comment]
Glad to hear that. Thanks for using this library 🙂
