### ISSUE TITLE
notifications.filter is not a function

### ISSUE THREAD

**Issue by mohit-github** [LouisBarranqueiro/reapop#46]
### Configuration

 - **Operating system with version** : Ubuntu 16.04
 - **Browser with version** : Chrome latest 59
 - **Reapop version** : 1.1.1
 - **React version** : 15.5.4
 - **Redux version** : 3.5.2
 - **React-redux version** : 4.4.5 
 

### Actual behavior
notifications.filter is not a function

### Expected behavior
Run without errors.

### Steps to reproduce the behavior
I just did the initial configuration and it throws this error.

I also went through the NotificationsSystem component in lib/components and the error is thrown at line numbers 65 and 79 (where notifcations.filter is called).

**Comment by LouisBarranqueiro** [comment]
Hi @mohit-github,  could you please show me your code (reducers configuration, etcc.)

**Comment by Clafouti** [comment]
I'm late to the party but I might have an idea for this issue.

Be careful to provide:

`
var reducer = combineReducers({
  // insert your reducers here
  notifications: notificationsReducer()
)};
`
The important part is that `notificationsReducer()` is a function (I just did that mistake and got this error).

**Comment by LouisBarranqueiro** [comment]
I guess It's this yeah. Thanks @Clafouti
