### ISSUE TITLE
Wrong default class for NotificationIcon

### ISSUE THREAD

**Issue by raress96** [LouisBarranqueiro/reapop#460]
### Description
The NotificationIcon has as default class the `notificationDismissIcon` instead of the `notificationIcon`, probably a typo:
https://github.com/LouisBarranqueiro/reapop/blob/main/src/components/NotificationIcon.tsx#L18

### Expected behavior
Replace the default class `notificationDismissIcon` with the class `notificationIcon`.

### Steps to reproduce the bug
Try to style the NotificationIcon using css.

**Comment by LouisBarranqueiro** [comment]
👋 @raress96 , indeed, sorry for the late reply. I'm gonna fix that right away.
