### ISSUE TITLE
reapop@4.0.4 doesn't have "dist" folder in it

### ISSUE THREAD

**Issue by shehi** [LouisBarranqueiro/reapop#466]
### Description
As title implies, v4.0.4 npm package doesn't have `dist` folder with source code in it. As such, that release is unusable.

**Comment by LouisBarranqueiro** [comment]
👋 @shehi, yes, I just realized that as many project failed to be updated. I don't know what happened. I will invalidate this release and made a new one.

**Comment by hiroshi80** [comment]
I have the same symptoms with v4.0.4. But, In v4.0.2 `dist` folder was installed.

**Comment by LouisBarranqueiro** [comment]
I re-published it under v4.0.5. It should be good now. Sorry about that guys. 👍
