### ISSUE TITLE
Integration with MaterialUI themes

### ISSUE THREAD

**Issue by MistyKuu** [LouisBarranqueiro/reapop#5]
Any chance to have it?

**Comment by LouisBarranqueiro** [comment]
Hey @MistyKuu , does they have an alert component or notification component?

**Comment by MistyKuu** [comment]
They have a snackbar: http://www.material-ui.com/#/components/snackbar

**Comment by LouisBarranqueiro** [comment]
I currently don't have time to create this theme, but I wrote a section to learn how to create a theme. You can also check existing theme as examples  : [Customize or create a theme](https://github.com/LouisBarranqueiro/reapop/blob/master/docs/api.md#customize-or-create-a-theme) :)
