### ISSUE TITLE
Mutation detected

### ISSUE THREAD

**Issue by NeXTs** [LouisBarranqueiro/reapop#501]
### Description
I use react component inside message. I need to update the message after some time. Here's the snippet.
```
import React from "react";
...

const notif = notify({
  message: (
    <div>1</div>
  ),
  status: "none"
});
const prevNotif = notif.payload;
dispatch(notif);

setTimeout(function() {
  prevNotif.message = (
    <div>2</div>
  );
  dispatch(notify(prevNotif));
}, 1000);
 
 ```
The update works, but in console I see this message

> Uncaught (in promise) Invariant Violation: A state mutation was detected between dispatches, in the path `notifications.0.message._store.validated`. This may cause incorrect behavior.

### Expected behavior
There should not be mutation.

### Environment
 - **OS name and version** : macOS Monterey 12.5.1
 - **Browser name and version**: Chrome 104.0.5112.101
 - **Reapop version**: 4.0.5

### Additional information
- [ ] I can fix this bug 
It worked well (without mutation) in v2.1.0

**Comment by LouisBarranqueiro** [comment]
👋 @NeXTs, thanks for reporting this issue. I will have a look at it right now. Getting back to you soon.

**Comment by NeXTs** [comment]
I should mention that this message was made by redux-immutable-state-invariant which runs only in dev mode.

To get rid of this error, as a temporarily solution I just ignored ‘notification’ branch in redux

```
const reduxImmutableStateInvariant = require("redux-immutable-state-invariant").default;
  middleWares.push(
    reduxImmutableStateInvariant({
      ignore: "notifications"
    })
  );
```

**Comment by LouisBarranqueiro** [comment]
@NeXTs could you please modify the demo and more precisely this [portion of code](https://github.com/LouisBarranqueiro/reapop/blob/89be61e60ef53cfaee9f46bb4b73583aefdaddbe/demo/src/components/Demo/Demo.tsx#L25) so I can reproduce this error easily?

**Comment by NeXTs** [comment]
I am not sure that there is anything you can do with it, since `_store.validated` is build-in React property which works in dev environment only. And since I put the react component in redux, it's not surprising that this happened.
The main thing for me is that it will not be reproduced in a production environment. So the decision to ignore the error message on the development environment is satisfactory for me.
