### ISSUE TITLE
Specify Message Tag

### ISSUE THREAD

**Issue by NeXTs** [LouisBarranqueiro/reapop#502]
### Description
I want to be able to specify [tag of Message](https://github.com/LouisBarranqueiro/reapop/blob/main/src/components/Notification.tsx#L64) component. I need to do it `div` instead of `p`

### Explanation / motivation
Because I inserted React component inside Message and receive a warning
`Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.`

### Additional information
- [ ] I can implement this feature/improvement

**Comment by NeXTs** [comment]
@LouisBarranqueiro do you need it to be `p`? What downsides if it will be changed to `div` by default?

**Comment by LouisBarranqueiro** [comment]
👋 , I don't remember exactly why I put a `p` instead of `div` I guess because I didn't think about your use case. Tested with a `div` and it looks the same. gonna make the change.
