### ISSUE TITLE
Cut a new release on npm

### ISSUE THREAD

**Issue by paintedbicycle** [LouisBarranqueiro/reapop#503]
### Description

It's been a while since the last release and there has been some updates including support for React 18 since the last release. Is the project in a state where a new release could be cut?

**Comment by augiwan** [comment]
+1 Waiting to try reapop! Please push a new release which supports react 18!

**Comment by shehi** [comment]
+1 here. Need React 18 support plz.

**Comment by LouisBarranqueiro** [comment]
👋 @paintedbicycle, sorry for the late reply. I've been off for a moment. Yes, I will release one in a few days. Gonna fix bugs first.

@augiwan @shehi 👋 guys, the package already supports React v18. The demo works with React v18. What's not working on your side? Please open issues to report these problems with the exact React version you use.

**Comment by shehi** [comment]
@LouisBarranqueiro check package.json of your latest release? 😀

**Comment by LouisBarranqueiro** [comment]
oh, interesting, you're right. I'm surprised I didn't release a new version since then. I will release one in a few days.

**Comment by NeXTs** [comment]
Since #502 will be included, I am waiting for the next release so much 🙏

**Comment by shehi** [comment]
Issue closed without any release :P
