### ISSUE TITLE
IE11 not support 

### ISSUE THREAD

**Issue by dongcer** [LouisBarranqueiro/reapop#509]
### Description

In the IE11 browser environment, the browser crashes by calling the notify function

### Expected behavior

There should be a compatibility scheme that does not crash

### Steps to reproduce the bug
 
There should be a compatibility scheme that does not crash

### Environment
 - **OS name and version** : 
 - **ie11**:
 - **Reapop version:4.2.0**:

### Additional information
- [ ] I can fix this bug

**Comment by dongcer** [comment]
Object does not support the animate property or method

**Comment by LouisBarranqueiro** [comment]
👋 @dongcer, could you please share the stacktrace with me please? But from what I can understand, your application is missing polyfill for IE. It is intended that the library does not include polyfills for all browsers to keep the library lightweight. It's up to the developer to include them if they need them.

**Comment by LouisBarranqueiro** [comment]
> 👋 @dongcer, could you please share the stacktrace with me please? But from what I can understand, your application is missing polyfill for IE. It is intended that the library does not include polyfills for all browsers to keep the library lightweight. It's up to the developer to include them if they need them.

Feel free to reopen this issue if you still encounter a problem.
