### ISSUE TITLE
Improvement - have current state in notifier - dismissed,open

### ISSUE THREAD

**Issue by anubhavsrivastava** [LouisBarranqueiro/reapop#52]
Currently, we have support to use same notifier instance to be updated via updateNotification.
but that instance doesn't provide information whether it is dismissed or is visible.
There is configuration 'onAdd', 'onRemove' will runs on Mounting/Un-mounting.

Notifier instance should have state whether instance was dismissed or still open.
consider,
 ```
if(this.notifier)
      {
        Object.assign(this.notifier, notificationData);
        updateNotification(this.notifier)
      }
    else 
      {
        this.notifier = notify(notificationData);
      } 
```
 if this.notifier is dismissed there is no way to create new instance.

**Comment by LouisBarranqueiro** [comment]
👋  @anubhavsrivastava, why do you need this? What's your use case? I mean if you plan to update a notification in your code, I guess you did the necessary to keep it visible.

**Comment by anubhavsrivastava** [comment]
Use case: display single toaster and update itself if there is new message(notification) instead of popping up another one.

Above code works fine for ensuring there is single instance but if the notification fades out, notification object is updated but notification isn't shown any further since previous one was dismissed after timeout.

**Comment by LouisBarranqueiro** [comment]
Sorry for the late response. I understand. Instead of having state of notifications which would increase complexity. I propose to `updateNotification` action to display a new notification if it does not exist and update the notification it does. What do you think?

**Comment by LouisBarranqueiro** [comment]
👋 @anubhavsrivastava, I released a new version with a new action [notify](https://github.com/LouisBarranqueiro/reapop/blob/master/docs/api.md#update-or-create-a-notification), It should solve your problem.

**Comment by anubhavsrivastava** [comment]
Yes this solves the problem completely.

**Comment by LouisBarranqueiro** [comment]
Happy to hear that! :)
