### ISSUE TITLE
Close notification programatically

### ISSUE THREAD

**Issue by msanandrea** [LouisBarranqueiro/reapop#526]
When I create a `loading` type notification, I won't use the `dismissAfter` property as I won't know how much time would I need. Based on this, how can I dismiss the notification from code? My guess would be I should be able to do something like this.

`const notification = notify(...);
notification.close();
`
I'm missing something here or this is a feature request?

**Comment by TobiasGrether** [comment]
Hey there,

I just looked around in the code a bit.
While there is no direct support for promises, you should be able to easily integrate that yourself.

`
    const updatedNotification = () => {
        const notif = dispatch(
            notify({
                id: 'updated-notification',
                title: 'Repository transfer',
                message: 'Your repository is being transfered...',
                position: POSITIONS.topRight,
                status: STATUSES.loading,
                dismissible: false,
                dismissAfter: 0,
            })
        ).payload

        setTimeout(() => {
            notif.status = STATUSES.success
            notif.message = 'Your repository have been transfered.'
            notif.buttons = [{name: 'OK', primary: true}, {name: 'Details'}]
            dispatch(notify(notif))
        }, 3000)
    }
`

This is taken straight from the Demo code. You could replace the setTimeout() call with a promise.then() to achieve the same result from what I can see,

Kind regards,
Tobias Grether

**Comment by TobiasGrether** [comment]
I wrote this simple typescript code to make it easier to write this without repetition:

```ts
declare type NotificationRequestOptions = {
    loading?: {
        title?: string;
        message?: string;
    },
    success?: {
        title?: string;
        message?: string;
        buttons?: NotificationButton[];
    },
    error?: {
        title?: string;
        buttons?: NotificationButton[];
    }
}
export function NotificationRequestHelper<T>(notify: (notification: Partial<Notification>) => Notification, promise: Promise<Response<T>>, options: NotificationRequestOptions): Promise<Response<T>> {
    const notif = notify({
        title: options.loading?.title ?? "",
        message: options.loading?.message ?? "",
        position: POSITIONS.topRight,
        status: STATUSES.loading,
        dismissible: false,
        dismissAfter: 0,
    })

    return promise.then((response) => {
            const {data, error} = response
            if (error) {
                notif.status = STATUSES.error
                notif.title = options.error?.title
                notif.dismissible = true
                notif.dismissAfter = 5 * 1000
                notif.message = error.message
                notif.buttons = options.error?.buttons ?? []
            } else {
                notif.status = STATUSES.success
                notif.title = options.success?.title
                notif.dismissible = true
                notif.dismissAfter = 5 * 1000
                notif.message = options.success?.message
                notif.buttons = options.success?.buttons ?? []
            }

            notify(notif)

            return response
        }
    )
}```

**Comment by LouisBarranqueiro** [comment]
👋 @msanandrea Sorry for the very late reply, I was on vacation. Thanks for your help @TobiasGrether. 🙏 

> `const notification = notify(...); notification.close(); `

Would that work for you?
``` js
const notif = dispatch(notify(...)).payload
// when you want to close the notification
dispatch(dismissNotification(notif.id))
```

**Comment by LouisBarranqueiro** [comment]
@msanandrea  I'm closing this issue as it is inactive. Feel free to re-open it to continue the discussion 🙂
