### ISSUE TITLE
Swipe to dismiss?

### ISSUE THREAD

**Issue by pixelwiz** [LouisBarranqueiro/reapop#54]
Is it possible to dismiss the notifications with a swipe on touch devices?

**Comment by LouisBarranqueiro** [comment]
I do not plan to handle touch events for the moment but let's keep this one open to see if some people need this feature 😃

**Comment by LouisBarranqueiro** [comment]
I'm closing this one for now. I'll reopen it if a lot more users need it.

**Comment by sorsaffari** [comment]
Could we consider reopening this? 8 👍s, not bad 🙁
