### ISSUE TITLE
Theme and Transition not working in demo

### ISSUE THREAD

**Issue by karmatys8** [LouisBarranqueiro/reapop#562]
### Description

When using your [demo](https://louisbarranqueiro.github.io/reapop/), I tried to change both Theme and Transition values, but encountered an issue where the changes did not take effect.

I even looked at the HTML and every single toast looked the same.

### Expected behavior

The Theme and Transition options should dynamically change the appearance and transition style of the toasts based on the selections made in the **Notification Creator**.

### Steps to reproduce the bug

1. Go to [demo](https://louisbarranqueiro.github.io/reapop/).
2. Modify either Theme or Transition option on the **Notification Creator**.
3. Then click **Notify** button.

### Environment
 - **OS name and version** : Windows 10
 - **Browser name and version**: Chrome Version 121.0.6167.189 (Official Build) (64-bit) *and* Firefox 123.0 (64-bit)
 - **Reapop version**: Does not apply

### Additional information
- [x] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
👋 @karmatys8, indeed, it does not work. Thanks for reporting that issue. I'm on it 👍
