### ISSUE TITLE
does it support customized component as children?

### ISSUE THREAD

**Issue by gm3000** [LouisBarranqueiro/reapop#65]
### Configuration

 - **Operating system with version** : 
 - **Browser with version** : 
 - **Reapop version** : 
 - **React version** : 
 - **Redux version** : 
 - **React-redux version** : 
 

### Expected behavior
It`ll be great if it supports customized component

**Comment by LouisBarranqueiro** [comment]
Hi @gm3000, be more specific please. Give me an example. What's the final goal of this?
