### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by Archakov06** [LouisBarranqueiro/reapop#66]
### Configuration

 - **Operating system with version** : macOS 10.12.6 (16G29)
 - **Browser with version** : Chrome 63
 - **Reapop version** : latest
 - **React version** : ^16.2.0
 - **Redux version** : ^3.7.2
 - **React-redux version** : ^5.0.6
 
When I call the method `notify`, I get an error: `TypeError: Object(...) is not a function`

I want to call a method `notify` when executing my action. Followed by the instructions, but for some reason nothing happens.

action.js
```js
import { notify } from 'reapop';

export const fetchSelectVariant = (type, id, variant, callback) => dispatch => {
  dispatch(
    notify({
      title: 'Upload status',
      message: 'Your file is uploading...',
      status: 'info'
    }),
  );
};
```

**Comment by LouisBarranqueiro** [comment]
👋 @Archakov06 , 11 days ago, the version with the `notify` action was not released. update Reapop module, it should be good now :)
