### ISSUE TITLE
Feature Request: support FontAwesome v5

### ISSUE THREAD

**Issue by microdou** [LouisBarranqueiro/reapop#67]
Icon does not work anymore under `FontAwesome v5`, which uses `svg` and `js` instead of `font`.
Please consider supporting `FontAwesome v5` by `react-fontawesome`.

**Comment by LouisBarranqueiro** [comment]
👋 @microdou, I do not plan to do it for the moment because I have to change Reapop and all its theme to support JS/SVG and CSS way at the same time. 

Best solution for the moment, is to include CSS file `fontawesome-all.min.css` (35KB) you need in your app. It will do the job. 

I will let you know when I'll start working on it.

**Comment by MartinSeeler** [comment]
Thanks for the hint! I use FontAwesome 5 via CDN but didn't noticed the different versions with svg+js and css. 

By switching to 
```html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">
```

everything works fine and the bug is gone.

**Comment by microdou** [comment]
@LouisBarranqueiro The `css` workaround works great! Thanks!

I'm using `webpack` and `react`. Instead of including a link referring to an external css file, I installed the css package `font-awesome-5-css` via `npm`. And it also works :)

**Comment by LouisBarranqueiro** [comment]
Cool. 😎  I was afraid you installed FA5 to use their new features related to JS/SVG. I'm closing this issue for the moment until more people need to integrate it using JS/SVG.

**Comment by microdou** [comment]
@LouisBarranqueiro Unfortunately, yes, I'm using the new feature JS/SVG... So basically I'm now using both as a workaround for reapop. JS/SVG removed the need of fonts, and can be smaller after compilation. Still hope it can be implemented in future. Thanks.

**Comment by LouisBarranqueiro** [comment]
@microdou I'll do it if a lot of people need this because it requires a lot of changes I think.

**Comment by microdou** [comment]
@LouisBarranqueiro Thanks. That's quite reasonable. Anyway I've made `font-awesome v5` work in my project by locally changing some reapop code. Now not extra font is needed :) It only works for `v5` though. It would be tricky to make it compatible to both `v4` and `v5`.
