### ISSUE TITLE
Smooth collapsing

### ISSUE THREAD

**Issue by NeXTs** [LouisBarranqueiro/reapop#7]
Hey

If you show first notification and after one second show another notification, then after first one hides - second one will instantly jump to position of first. Instantly. Doesn't it annoy you?

How about making it as smooth as here?
![stack](https://cloud.githubusercontent.com/assets/1753208/18724032/9582fd2a-8043-11e6-85f4-edac06df5865.gif)

Took from [react-notification](https://github.com/pburtchaell/react-notification)

It's UI component, such small things matters :)

**Comment by LouisBarranqueiro** [comment]
Hey @NeXTs , yeah, it would be great, I currently dont have time to implement a feature like this. and you? Not sure, if it is possible with some css transition (`TranslateY`) to achieve this trick. But I'm gonna think about because yeah, it's smoother :)

**Comment by NeXTs** [comment]
`TranslateY`?
I'd make it simpler. By animating max-height of hidding notification by simple css rule. So that upper notifications would move accordingly

**Comment by LouisBarranqueiro** [comment]
yeah but if we animate the height of the notification, it changes the actual transition. Currently, the notification swipe out of the screen. a trick would to swipe the notification out of the screen and then animate its height. But it would increase the animation time.

**Comment by NeXTs** [comment]
I guess we could add delay before changing height
But what's the problem with increasing animation time?

**Comment by LouisBarranqueiro** [comment]
nothing really important, but long animation can be annoying ( in term of UX) but let's try this :) I'm gonna do that today or tomorrow :)

**Comment by NeXTs** [comment]
Cool!

Honestly, I don't get what you meant saying it'll increase animation time.
Yes, adding delay before changing max-height will increase whole "hiding" animation effect, like, twice.
But user will not be aware of that.
Because second part of animation (max-height) will be executed out of the window, user won't be aware of that at all (if he had only one notification. if he had two or more - animation would looks exact as at attached gif).
First part of animation (transition out of the window) should stay same, doesn't it?
That's how I see it

**Comment by LouisBarranqueiro** [comment]
I mean time to have the second animation at the top.
E.g : 
- swipe out : 200ms
- slide up : 200ms 
so 400ms
instead of 200ms currently, but I agree with you it's not really important,  and it gonna be smooth :)

**Comment by LouisBarranqueiro** [comment]
Since notification div has `display:table` property, we can use the `max-height` trick on it. 

We can't completely remove `display:table` on notification div otherwise it break position and height of buttons. 

the aim would be to :
1. swipe out notification
2. apply `display:block`
3. animate max-height

key-frames are perfect for this but we can't use `display` property because they are ignored.I'm still on it to find a work-around

Do you have an idea to solve this with only CSS ?

For the moment, animations are only handled by themes to allow a theme to create its own animation, so it's would be great to keep it like this.

**Comment by NeXTs** [comment]
I believe you can wrap table in div with overflow hidden and change height
of wrapper instead. Or you could completely steal solution from plugin I
provided in first post))

воскресенье, 9 октября 2016 г. пользователь Louis Barranqueiro написал:

**Comment by LouisBarranqueiro** [comment]
![reapop-smooth](https://cloud.githubusercontent.com/assets/4705626/19220284/4916564a-8e2a-11e6-85e2-a94216abde5a.gif)

**Comment by LouisBarranqueiro** [comment]
now i'm gonna :
- update Reapop to add the wrapper with a className instead of applying style with `style` attribute
- add a className on each theme to stylize the wrapper

**Comment by LouisBarranqueiro** [comment]
https://github.com/LouisBarranqueiro/reapop/releases/tag/v0.6.0

**Comment by NeXTs** [comment]
Great job @LouisBarranqueiro, thanks! :)

**Comment by LouisBarranqueiro** [comment]
@NeXTs Thanks for this good idea :)
