### ISSUE TITLE
Hide notification based on ID

### ISSUE THREAD

**Issue by archiekd** [LouisBarranqueiro/reapop#71]
Been implementing your notification solution which is great however I have stumbled upon the situation where I would like the notification to appear unless the user has actively dismissed it, however, I would like to keep bringing it up if the user hasn't dismissed it previously.

Would this be something that you could add, I was thinking something along the lines of

```javascript
hideNotification(notificationId)
```

**Comment by LouisBarranqueiro** [comment]
👋 @archiekd , please describe more precisely your use case. I'm not sure if I understood your problem but you add a notification then you want to update this one unless the user decided to hide it, right? If yes, use `notify` for the first notification then use `updateNotification` to update it. It will not create a notification if this one has been removed.
