### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by pantchox** [LouisBarranqueiro/reapop#72]
### Configuration

 - **Operating system with version** : windows 7
 - **Browser with version** :  chrome
 - **Reapop version** :  1.2.0
 - **React version** :  15.1
 - **Redux version** :  3.3.1
 - **React-redux version** : 4.4.1 
 
Hi
I am using React with server side rendering, i understand there is no window object on SSR but is there a workaround to calculate the window only when elements are rendered?

the error is in `node_modules\reapop\lib\components\NotificationsSystem.js:51:20`

thanks!

**Comment by LouisBarranqueiro** [comment]
👋 @pantchox 

`NotificationsSystem` component needs to know the size of the window to choose where we display notifications (at the top of the screen or on the default position).

We could use top position if we cannot determine window width (`window not defined`), then register an event when the DOM is loaded, so we get the window width and re-render the component. I don't that much about server side rendering. Do you know if this could be possible?

**Comment by pantchox** [comment]
Hi,

This is a great idea!
I am just using a boilerplate that uses SSR, so i am not an expert.

SSR is almost the same as regular react, just that there are some constraints because of global objects issues, since the first render happens on node and then sent as a static page to the client while it waits till the JS bundle will load and then it will take it from there.

If you search for "SSR react window not defined" i am sure you will find solutions that are suitable for this library,  for me its hard to say since i didn't create it (reapop) but it seems this issue happens in many visualization JS libraries that already found a solution to this.

**Comment by pantchox** [comment]
Hi,

any news with this?

**Comment by LouisBarranqueiro** [comment]
@pantchox, not yet. Could you please send me a complete example (a dockerized project would be the best) that I can use to reproduce this bug and write a fix.

**Comment by LouisBarranqueiro** [comment]
👋 @pantchox, I'm closing this one for now. Feel free to re-open it when you have a complete example.
