### ISSUE TITLE
Support Redux 4

### ISSUE THREAD

**Issue by leinelissen** [LouisBarranqueiro/reapop#74]
A new version of Redux was released about a week ago. I'm using it right now in a new app I am making, and reapop seems to handle it well. The package.json explicitly specifies the package to work with Redux 2 and 3 only, thus resulting in an error on install.

Could we bump the dependency?

[Redux 4 announcement](https://github.com/reactjs/redux/releases/tag/v4.0.0)

**Comment by LouisBarranqueiro** [comment]
👋 @leinelissen , i'm gonna add redux 4 in the tests suite then yes, I'll update peer dependencies :)

**Comment by leinelissen** [comment]
Thank you very much!

**Comment by alex-karo** [comment]
Seems to be current tests pass and demo works fine. How can I help you for close the issue?

**Comment by LouisBarranqueiro** [comment]
@alex-karo the build does not pass with a few configurations. I have to update them.
