### ISSUE TITLE
Feat Request : Toaster with inverted progress bar showing time to dismiss

### ISSUE THREAD

**Issue by lucasverra** [LouisBarranqueiro/reapop#77]
I think i've seen that on Binance or Kraken :)

**Comment by LouisBarranqueiro** [comment]
👋 @lucasverra, that's something I don't want to spend time on because it's not so useful IMO. I will re-consider it if more people want this.

**Comment by NeXTs** [comment]
Maybe it's not useful but it [looks good](https://dribbble.com/shots/9656270-Toast-Notification), +1 for this
