### ISSUE TITLE
Dismissible does not work with default notification

### ISSUE THREAD

**Issue by Levino** [LouisBarranqueiro/reapop#81]
From yarn.lock
```bash
reapop@^2.0.0:
  version "2.0.0"
  resolved "https://registry.npmjs.org/reapop/-/reapop-2.0.0.tgz#7e49507509950c3eef581a965a5de0d4238f9899"
  dependencies:
    prop-types "^15.6.0"
    react-transition-group "^2.2.1"
```

### Actual behavior
Notification is not dismissible by clicking on it.

### Expected behavior
Notification is dismissible by clicking on it.

### Steps to reproduce the behavior
1. Use this default notification when creating the reducer
    ```js
    // default value for notifications
    const defaultNotification = {
      dismissAfter: 60000,
      dismissible: true,
      position: 'bc',
      status: 'info',
    }
    ```
    (I am sure I correctly applied the object because notifications show for 60 seconds at the bottom, centered).
1. Create a notification like so:
    ```js
    import { notify } from 'reapop'
    notify({
      message: 'I failed!',
      status: 'error',
      title: `Something went wrong when honking`,
    })
    ```
1. Verify that notification is not dismissible.

Remark:
Creating the notification like so works:
```js
import { notify } from 'reapop'
notify({
  message: 'I failed!',
  status: 'error',
  dismissible: true,
  title: `Something went wrong when honking`,
})

**Comment by Levino** [comment]
Same holds for buttons.

**Comment by dpmango** [comment]
Same issue

**Comment by LouisBarranqueiro** [comment]
👋  guys, sorry for the late I was on vacations. I'm gonna take care of that this WE.
