### ISSUE TITLE
Unnecessary Semicolon

### ISSUE THREAD

**Issue by CodeSlip** [LouisBarranqueiro/reapop#87]
Receiving the following error after importing the requisite packages into my app - any suggestions on a fix? Sorry a little late on my end.

ERROR in ./node_modules/reapop-theme-wybo/lib/styles.css (./node_modules/css-loader??ref--6-1!./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src!./node_modules/reapop-theme-wybo/lib/styles.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(1:17) Unnecessary semicolon

> 1 | @charset "UTF-8";
    |                 ^
  2 | /**
  3 |  * Mixin to create a keyframes for a notification

The following is my webpack config:

const path = require('path');
const webpack = require('webpack');
var CSSLoader = [
  'css-loader?sourceMap&-minimize',
  'modules',
  'importLoaders=1',
  'localIdentName=[name]__[local]__[hash:base64:5]'
].join('&');

module.exports = {
  devtool: 'cheap-module-eval-source-map',
  entry: [
    // 'webpack-hot-middleware/client',
    'babel-polyfill',
    path.join(__dirname, '../src/web/index'),
  ],
  output: {
    path: path.join(__dirname, '../src/web'),
    filename: 'bundle.js',
    publicPath: '/',
  },
  module: {
    rules: [
      // Take all sass files, compile them, and bundle them in with our js bundle
      {
        test: /\.html$/,
        use: [
          { loader: 'html-loader' }
        ],
      },
      {
        test: /\.scss$/,
        use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 1 } },
          'sass-loader',
        ],
      },
      {
        test: /\.css$/,
        use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 1 } },
          { loader: CSSLoader, options: { importLoaders: 1}},
          'postcss-loader',
        ],
      },
      {
        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url-loader?limit=10000&minetype=application/font-woff'
      }, {
        test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'file-loader'
      },
      {
        test: /\.json$/,
        loader: 'json-loader',
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {
          presets: ['es2015', 'react', 'stage-0'],
          plugins: [
            [
              'react-transform',
              {
                transforms: [
                  {
                    transform: 'react-transform-hmr',
                    imports: ['react'],
                    // this is important for Webpack HMR:
                    locals: ['module'],
                  },
                ],
              },
            ],
          ],
        },
      },
    ],
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('development'),
        PLATFORM_ENV: JSON.stringify('web'),
      },
    }),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
//Edit the logo in the brower to make the app official
    new webpack.LoaderOptionsPlugin({
      options: {
        historyApiFallback: {
          index: path.join(__dirname, '../src/web/index'),
          rewrites: [
            //shows favicon
            { from: /favicon.ico/, to: '../src/images/herd.ico' }]
         }
        }
      })
  ],
};

**Comment by LouisBarranqueiro** [comment]
👋 @CodeSlip, sorry for the late response.

Webpack probably does not use the correct loader for this file. Could you please format your webpack config correctly so I understand it?

**Comment by LouisBarranqueiro** [comment]
Feel free to re-open this issue if you still encounter this problem.
